### ISSUE TITLE
Swagger UI

### ISSUE THREAD

**Issue by panbhatt** [BlueOakJS/blueoak-server#44]
Is there is a way through which we can directly launch the swagger UI on the browser and check whether the API is working or not. 
In addition, do we have an authentication module available to verify the authenticity of the request. 
Rest the project seems a great one.. looking forward.

**Comment by pwwolf** [comment]
That's a great suggestion @panbhatt -- we are looking at adding swagger UI.

Regarding authentication, I'm working on the documentation for the the auth system.  Right now we have google oauth and google JWT support built in, but I want to add a method for plugging in passport modules.

**Comment by panbhatt** [comment]
Thanks. that seems a great move in right direction. Appreciate, if we can provide a way for a developer to associate his custom authentication module (also as of passport, we tried passport however passport makes a number of redundant calls to REDIS or other storage), so we replaced passport with our own authenticaton that is being invoked an all URI except login/logout. 
Eagerly waiting for the documentation, that will be a great idea.

**Comment by seanpk** [comment]
It looks like **2.1.0-beta.2** is good for providing the constructed swagger definitions to the network.  
(I installed it by doing `npm install blueoak-server@beta` in my project directory.)

Since my server has CORS enabled, I also had to add the location of my [swagger-ui](https://github.com/swagger-api/swagger-ui) instance to the `cors.origin` array in `config/default.json`.

That done, with blueoak-server running, I can load the API in Swagger UI by giving it the URL to my spec, e.g.: `http://localhost:3000/swagger/my-swagger-spec`  
(Each swagger file in `swagger/` is exposed in this way, so I can also use `http://localhost:3000/swagger/my-other-swagger-spec`.)

**Comment by seanpk** [comment]
@pwwolf - I think it could also be useful for the swagger specs to be available through a service, maybe a `swagger` service?

While there may be other uses, I'm primarily thinking about how I might implement a deeper integration with Swagger UI so I could use it to serve API docs to consumers of my API.

For me this would be a "nice-to-have" for 2.1.0.

**Comment by pwwolf** [comment]
@seanpk , opened #46 for the swagger service work.

**Comment by seanpk** [comment]
for an idea of the "state of the art" for working with swagger specs and BOS, see: #65 

I'm going to close this issue ... subscribe to #9 for updates about authentication and authorization support enhancements
