### ISSUE TITLE
Swagger handling breaks on x-www-form-urlencoded bodies

### ISSUE THREAD

**Issue by jeff-lee-ps** [BlueOakJS/blueoak-server#72]
I was playing with the blueoak-server 2.4.3 + swagger definitions this morning and ran into a problem related to defining a formData parameter.

consumes:
        - application/x-www-form-urlencoded
parameters:
        - name: test2
          in: formData
          description: test param
          required: true
          type: string

Error on console:
debug: -swagger - Wiring up route post /other2 to other.other2Set
TypeError: Cannot read property 'fields' of undefined
    at registerRoute (/Users/jefflee/project/node_modules/blueoak-server/handlers/_swagger.js:247:42)

When I look at the _swagger.js file, the problem is it's trying to use _upload.fields inside a containsFormData() block; however, _upload is only set in a containsMultiPartFormData() block.

**Comment by seanpk** [comment]
@ryshep111 - I know you've been looking at this. Please mention this in the eventual PR.

**Comment by ryshep111** [comment]
So after digging deeper, it looks like whoever wrote that code wanted multer middleware configured for ANY form data because multer puts non file parameters that it finds in the request body. However, multer should indeed only be used for multipart/form-data, thus body parser MUST be configured for form data that is not multi part.  Will need to add an extra check for this.

**Comment by ryshep111** [comment]
[PR submitted](../pull/73)
